### ISSUE TITLE
Add DSP status endpoint `/v1/dsp/alive`

### ISSUE THREAD

**Issue by DenisCarriere** [liquidapps-io/zeus-sdk#2]
For ease of monitoring the DSP software to check if it's running properly, it would be ideal to have a basic status update endpoint.

## Example

**endpoint**

- `/v1/dsp/alive`

**response**

```json
{
  "status": "OK"
}
```

**Comment by NatPDeveloper** [comment]
We've added a status endpoint.

http://kylin-dsp-2.liquidapps.io/v1/dsp/version

Patch notes: https://docs.liquidapps.io/en/stable/patches/latest.html
