### ISSUE TITLE
Chess contracts not building

### ISSUE THREAD

**Issue by Dewald928** [liquidapps-io/zeus-sdk#30]
I tried running

```mkdir chess; cd chess
zeus box create
zeus unbox chess
zeus migrate
zeus run frontend main
```

But 'zeus migrate' is failing. Issue with the contracts.

**Comment by NatPDeveloper** [comment]
Hello @Dewald928 the reason for this is documented here: https://github.com/EOSIO/eosio.cdt/issues/1219

I've asked the b1 team for an update, but it's a ghost town over there lately and I doubt they'll fix this soon.

You can try compiling with older version of the CDT to see if it works.

The documentation for this is located here as well if that helps: https://developers.eos.io/welcome/v2.2/tools/history-tools/creating-wasms#building

**Comment by Dewald928** [comment]
Ah I see. Have you gotten it working with another CDT? In which case which version? 

I just wanted to use it as an example, so not the end of the world for me.
But now I know I need to watch out with this

**Comment by NatPDeveloper** [comment]
> Ah I see. Have you gotten it working with another CDT? In which case which version?
> 
> I just wanted to use it as an example, so not the end of the world for me. But now I know I need to watch out with this

I have not.

**Comment by NatPDeveloper** [comment]
I am closing this issue.  b1 has been lacking in their response times and pushing features.  I doubt they will get around to fixing this.
